modLoader = "javafml"
loaderVersion = "[43,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"

[[mods]]
modId = "aether"
version = "${file.jarVersion}"
displayName = "The Aether"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-aether"
logoFile = "aether.png"
credits = "Gilded Games for maintaining the Aether mod, the Aether Collaboration Team (Kingbdogz, Shockah, Kodaichi, Flan, and 303) for creating the original Aether mod, Modding Legacy (115kino, KingPhygieBoo, and Lachney) for originally porting and developing the mod in newer versions, and GitHub contributors for their help throughout development, as well as C4 for Curios API, the source code of which can be found at https://github.com/TheIllusiveC4/Curios"
authors = "bconlon, Burning Cactus, Drullkus, Hugo Payn, Jaryt, Oscar Payn, quek, Raptor, reetam"
description = '''
    Gilded Games presents the original Aether mod! Up to date for modern Minecraft versions and fully compatible with multiplayer. The Aether is a dimension of floating islands high in the sky. Ascend through a Glowstone portal and begin a new survival adventure packed with new ores, mythical creatures and perilous Dungeons!
    '''

[[dependencies.aether]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.1.1,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.19.2-5.1.1.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.aether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2]"
    ordering = "NONE"
    side = "BOTH"
