name: Add issues and PRs to project automatically
on: [issues, pull_request]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: Add Issues to Project
      uses: takanabe/github-actions-automate-projects@v0.0.2
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gilded-Games/The-Aether/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Back Log
    - name: Add PRs to Project
      uses: takanabe/github-actions-automate-projects@v0.0.2
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gilded-Games/The-Aether/projects/1
        GITHUB_PROJECT_COLUMN_NAME: In Progress
